'''
url: https://projecteuler.net/problem=2
Question 2:
Even Fibonacci Numbers

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

'''

def sum_of_even_fibonacci_numbers(n):
    fib_list = [1,2]
    while fib_list[-1] < n:
        fib_list.append(fib_list[-1] + fib_list[-2])
    
    return sum([x for x in fib_list if x % 2 == 0])

print(sum_of_even_fibonacci_numbers(4000000))
